// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SalaryWebService.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("SearchEmployeeByPrivateId", Description="\tThe feature checks for the correct work of the web service\r\n\tfor calculation sal" +
        "ary of employees. The feature checks \r\n\tthe function of search employee by priva" +
        "teId", SourceFile="Features\\SearchEmployeeByPrivateId.feature", SourceLine=0)]
    public partial class SearchEmployeeByPrivateIdFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SearchEmployeeByPrivateId.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SearchEmployeeByPrivateId", "\tThe feature checks for the correct work of the web service\r\n\tfor calculation sal" +
                    "ary of employees. The feature checks \r\n\tthe function of search employee by priva" +
                    "teId", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Search the employee by privateId", SourceLine=5)]
        public virtual void SearchTheEmployeeByPrivateId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search the employee by privateId", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "PrivateId",
                        "FirstName",
                        "LastName",
                        "MiddleName",
                        "Experiense",
                        "ProfessionId"});
            table1.AddRow(new string[] {
                        "666",
                        "10500id",
                        "Узбек",
                        "Ашан",
                        "Анатольевич",
                        "8",
                        "3"});
#line 7
 testRunner.Given("The employee created on the web service with the data", ((string)(null)), table1, "Given ");
#line 11
 testRunner.When("I search the employee on the web service by \'PrivateId\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Tag"});
            table2.AddRow(new string[] {
                        "private_id"});
            table2.AddRow(new string[] {
                        "last_name"});
            table2.AddRow(new string[] {
                        "first_name"});
            table2.AddRow(new string[] {
                        "middle_name"});
            table2.AddRow(new string[] {
                        "exp"});
            table2.AddRow(new string[] {
                        "prof_name"});
            table2.AddRow(new string[] {
                        "salary_amount"});
#line 12
 testRunner.Then("The web service response tags named and placed as", ((string)(null)), table2, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "PrivateId",
                        "FirstName",
                        "LastName",
                        "MiddleName",
                        "Experiense",
                        "ProfessionId"});
            table3.AddRow(new string[] {
                        "666",
                        "10500id",
                        "Узбек",
                        "Ашан",
                        "Анатольевич",
                        "8",
                        "3"});
#line 23
 testRunner.And("Data in the web service response match the employee with the data", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
